// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.etcd.jetcd.api;

public interface AuthRoleGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.AuthRoleGetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string role = 1;</code>
   */
  java.lang.String getRole();
  /**
   * <code>string role = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
