// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.etcd.jetcd.api;

/**
 * Protobuf type {@code etcdserverpb.MemberUpdateRequest}
 */
public  final class MemberUpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:etcdserverpb.MemberUpdateRequest)
    MemberUpdateRequestOrBuilder {
  // Use MemberUpdateRequest.newBuilder() to construct.
  private MemberUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MemberUpdateRequest() {
    iD_ = 0L;
    peerURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MemberUpdateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            iD_ = input.readUInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              peerURLs_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            peerURLs_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        peerURLs_ = peerURLs_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.etcd.jetcd.api.JetcdProto.internal_static_etcdserverpb_MemberUpdateRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.etcd.jetcd.api.JetcdProto.internal_static_etcdserverpb_MemberUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.etcd.jetcd.api.MemberUpdateRequest.class, io.etcd.jetcd.api.MemberUpdateRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long iD_;
  /**
   * <pre>
   * ID is the member ID of the member to update.
   * </pre>
   *
   * <code>uint64 ID = 1;</code>
   */
  public long getID() {
    return iD_;
  }

  public static final int PEERURLS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList peerURLs_;
  /**
   * <pre>
   * peerURLs is the new list of URLs the member will use to communicate with the cluster.
   * </pre>
   *
   * <code>repeated string peerURLs = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getPeerURLsList() {
    return peerURLs_;
  }
  /**
   * <pre>
   * peerURLs is the new list of URLs the member will use to communicate with the cluster.
   * </pre>
   *
   * <code>repeated string peerURLs = 2;</code>
   */
  public int getPeerURLsCount() {
    return peerURLs_.size();
  }
  /**
   * <pre>
   * peerURLs is the new list of URLs the member will use to communicate with the cluster.
   * </pre>
   *
   * <code>repeated string peerURLs = 2;</code>
   */
  public java.lang.String getPeerURLs(int index) {
    return peerURLs_.get(index);
  }
  /**
   * <pre>
   * peerURLs is the new list of URLs the member will use to communicate with the cluster.
   * </pre>
   *
   * <code>repeated string peerURLs = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPeerURLsBytes(int index) {
    return peerURLs_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (iD_ != 0L) {
      output.writeUInt64(1, iD_);
    }
    for (int i = 0; i < peerURLs_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, peerURLs_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (iD_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, iD_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < peerURLs_.size(); i++) {
        dataSize += computeStringSizeNoTag(peerURLs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPeerURLsList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.etcd.jetcd.api.MemberUpdateRequest)) {
      return super.equals(obj);
    }
    io.etcd.jetcd.api.MemberUpdateRequest other = (io.etcd.jetcd.api.MemberUpdateRequest) obj;

    boolean result = true;
    result = result && (getID()
        == other.getID());
    result = result && getPeerURLsList()
        .equals(other.getPeerURLsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getID());
    if (getPeerURLsCount() > 0) {
      hash = (37 * hash) + PEERURLS_FIELD_NUMBER;
      hash = (53 * hash) + getPeerURLsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.etcd.jetcd.api.MemberUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etcd.jetcd.api.MemberUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etcd.jetcd.api.MemberUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etcd.jetcd.api.MemberUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etcd.jetcd.api.MemberUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etcd.jetcd.api.MemberUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etcd.jetcd.api.MemberUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.etcd.jetcd.api.MemberUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etcd.jetcd.api.MemberUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etcd.jetcd.api.MemberUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.etcd.jetcd.api.MemberUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code etcdserverpb.MemberUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:etcdserverpb.MemberUpdateRequest)
      io.etcd.jetcd.api.MemberUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.etcd.jetcd.api.JetcdProto.internal_static_etcdserverpb_MemberUpdateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.etcd.jetcd.api.JetcdProto.internal_static_etcdserverpb_MemberUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.etcd.jetcd.api.MemberUpdateRequest.class, io.etcd.jetcd.api.MemberUpdateRequest.Builder.class);
    }

    // Construct using io.etcd.jetcd.api.MemberUpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      iD_ = 0L;

      peerURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.etcd.jetcd.api.JetcdProto.internal_static_etcdserverpb_MemberUpdateRequest_descriptor;
    }

    public io.etcd.jetcd.api.MemberUpdateRequest getDefaultInstanceForType() {
      return io.etcd.jetcd.api.MemberUpdateRequest.getDefaultInstance();
    }

    public io.etcd.jetcd.api.MemberUpdateRequest build() {
      io.etcd.jetcd.api.MemberUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.etcd.jetcd.api.MemberUpdateRequest buildPartial() {
      io.etcd.jetcd.api.MemberUpdateRequest result = new io.etcd.jetcd.api.MemberUpdateRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.iD_ = iD_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        peerURLs_ = peerURLs_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.peerURLs_ = peerURLs_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.etcd.jetcd.api.MemberUpdateRequest) {
        return mergeFrom((io.etcd.jetcd.api.MemberUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.etcd.jetcd.api.MemberUpdateRequest other) {
      if (other == io.etcd.jetcd.api.MemberUpdateRequest.getDefaultInstance()) return this;
      if (other.getID() != 0L) {
        setID(other.getID());
      }
      if (!other.peerURLs_.isEmpty()) {
        if (peerURLs_.isEmpty()) {
          peerURLs_ = other.peerURLs_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensurePeerURLsIsMutable();
          peerURLs_.addAll(other.peerURLs_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.etcd.jetcd.api.MemberUpdateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.etcd.jetcd.api.MemberUpdateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long iD_ ;
    /**
     * <pre>
     * ID is the member ID of the member to update.
     * </pre>
     *
     * <code>uint64 ID = 1;</code>
     */
    public long getID() {
      return iD_;
    }
    /**
     * <pre>
     * ID is the member ID of the member to update.
     * </pre>
     *
     * <code>uint64 ID = 1;</code>
     */
    public Builder setID(long value) {
      
      iD_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID is the member ID of the member to update.
     * </pre>
     *
     * <code>uint64 ID = 1;</code>
     */
    public Builder clearID() {
      
      iD_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList peerURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePeerURLsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        peerURLs_ = new com.google.protobuf.LazyStringArrayList(peerURLs_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * peerURLs is the new list of URLs the member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPeerURLsList() {
      return peerURLs_.getUnmodifiableView();
    }
    /**
     * <pre>
     * peerURLs is the new list of URLs the member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 2;</code>
     */
    public int getPeerURLsCount() {
      return peerURLs_.size();
    }
    /**
     * <pre>
     * peerURLs is the new list of URLs the member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 2;</code>
     */
    public java.lang.String getPeerURLs(int index) {
      return peerURLs_.get(index);
    }
    /**
     * <pre>
     * peerURLs is the new list of URLs the member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPeerURLsBytes(int index) {
      return peerURLs_.getByteString(index);
    }
    /**
     * <pre>
     * peerURLs is the new list of URLs the member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 2;</code>
     */
    public Builder setPeerURLs(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePeerURLsIsMutable();
      peerURLs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * peerURLs is the new list of URLs the member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 2;</code>
     */
    public Builder addPeerURLs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePeerURLsIsMutable();
      peerURLs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * peerURLs is the new list of URLs the member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 2;</code>
     */
    public Builder addAllPeerURLs(
        java.lang.Iterable<java.lang.String> values) {
      ensurePeerURLsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, peerURLs_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * peerURLs is the new list of URLs the member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 2;</code>
     */
    public Builder clearPeerURLs() {
      peerURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * peerURLs is the new list of URLs the member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 2;</code>
     */
    public Builder addPeerURLsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePeerURLsIsMutable();
      peerURLs_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:etcdserverpb.MemberUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:etcdserverpb.MemberUpdateRequest)
  private static final io.etcd.jetcd.api.MemberUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.etcd.jetcd.api.MemberUpdateRequest();
  }

  public static io.etcd.jetcd.api.MemberUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MemberUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<MemberUpdateRequest>() {
    public MemberUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MemberUpdateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MemberUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MemberUpdateRequest> getParserForType() {
    return PARSER;
  }

  public io.etcd.jetcd.api.MemberUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

