// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.etcd.jetcd.api;

public interface MemberListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.MemberListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  io.etcd.jetcd.api.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  io.etcd.jetcd.api.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * members is a list of all members associated with the cluster.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 2;</code>
   */
  java.util.List<io.etcd.jetcd.api.Member> 
      getMembersList();
  /**
   * <pre>
   * members is a list of all members associated with the cluster.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 2;</code>
   */
  io.etcd.jetcd.api.Member getMembers(int index);
  /**
   * <pre>
   * members is a list of all members associated with the cluster.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 2;</code>
   */
  int getMembersCount();
  /**
   * <pre>
   * members is a list of all members associated with the cluster.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 2;</code>
   */
  java.util.List<? extends io.etcd.jetcd.api.MemberOrBuilder> 
      getMembersOrBuilderList();
  /**
   * <pre>
   * members is a list of all members associated with the cluster.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 2;</code>
   */
  io.etcd.jetcd.api.MemberOrBuilder getMembersOrBuilder(
      int index);
}
