// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.etcd.jetcd.api;

public interface AuthRoleListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.AuthRoleListRequest)
    com.google.protobuf.MessageOrBuilder {
}
