// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election.proto

package io.etcd.jetcd.api;

/**
 * Protobuf type {@code v3electionpb.ResignRequest}
 */
public  final class ResignRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v3electionpb.ResignRequest)
    ResignRequestOrBuilder {
  // Use ResignRequest.newBuilder() to construct.
  private ResignRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResignRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ResignRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.etcd.jetcd.api.LeaderKey.Builder subBuilder = null;
            if (leader_ != null) {
              subBuilder = leader_.toBuilder();
            }
            leader_ = input.readMessage(io.etcd.jetcd.api.LeaderKey.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(leader_);
              leader_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.etcd.jetcd.api.ElectionOuterClass.internal_static_v3electionpb_ResignRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.etcd.jetcd.api.ElectionOuterClass.internal_static_v3electionpb_ResignRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.etcd.jetcd.api.ResignRequest.class, io.etcd.jetcd.api.ResignRequest.Builder.class);
  }

  public static final int LEADER_FIELD_NUMBER = 1;
  private io.etcd.jetcd.api.LeaderKey leader_;
  /**
   * <pre>
   * leader is the leadership to relinquish by resignation.
   * </pre>
   *
   * <code>.v3electionpb.LeaderKey leader = 1;</code>
   */
  public boolean hasLeader() {
    return leader_ != null;
  }
  /**
   * <pre>
   * leader is the leadership to relinquish by resignation.
   * </pre>
   *
   * <code>.v3electionpb.LeaderKey leader = 1;</code>
   */
  public io.etcd.jetcd.api.LeaderKey getLeader() {
    return leader_ == null ? io.etcd.jetcd.api.LeaderKey.getDefaultInstance() : leader_;
  }
  /**
   * <pre>
   * leader is the leadership to relinquish by resignation.
   * </pre>
   *
   * <code>.v3electionpb.LeaderKey leader = 1;</code>
   */
  public io.etcd.jetcd.api.LeaderKeyOrBuilder getLeaderOrBuilder() {
    return getLeader();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (leader_ != null) {
      output.writeMessage(1, getLeader());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (leader_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLeader());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.etcd.jetcd.api.ResignRequest)) {
      return super.equals(obj);
    }
    io.etcd.jetcd.api.ResignRequest other = (io.etcd.jetcd.api.ResignRequest) obj;

    boolean result = true;
    result = result && (hasLeader() == other.hasLeader());
    if (hasLeader()) {
      result = result && getLeader()
          .equals(other.getLeader());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLeader()) {
      hash = (37 * hash) + LEADER_FIELD_NUMBER;
      hash = (53 * hash) + getLeader().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.etcd.jetcd.api.ResignRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etcd.jetcd.api.ResignRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etcd.jetcd.api.ResignRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etcd.jetcd.api.ResignRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etcd.jetcd.api.ResignRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etcd.jetcd.api.ResignRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etcd.jetcd.api.ResignRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.etcd.jetcd.api.ResignRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etcd.jetcd.api.ResignRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etcd.jetcd.api.ResignRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.etcd.jetcd.api.ResignRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v3electionpb.ResignRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v3electionpb.ResignRequest)
      io.etcd.jetcd.api.ResignRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.etcd.jetcd.api.ElectionOuterClass.internal_static_v3electionpb_ResignRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.etcd.jetcd.api.ElectionOuterClass.internal_static_v3electionpb_ResignRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.etcd.jetcd.api.ResignRequest.class, io.etcd.jetcd.api.ResignRequest.Builder.class);
    }

    // Construct using io.etcd.jetcd.api.ResignRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (leaderBuilder_ == null) {
        leader_ = null;
      } else {
        leader_ = null;
        leaderBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.etcd.jetcd.api.ElectionOuterClass.internal_static_v3electionpb_ResignRequest_descriptor;
    }

    public io.etcd.jetcd.api.ResignRequest getDefaultInstanceForType() {
      return io.etcd.jetcd.api.ResignRequest.getDefaultInstance();
    }

    public io.etcd.jetcd.api.ResignRequest build() {
      io.etcd.jetcd.api.ResignRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.etcd.jetcd.api.ResignRequest buildPartial() {
      io.etcd.jetcd.api.ResignRequest result = new io.etcd.jetcd.api.ResignRequest(this);
      if (leaderBuilder_ == null) {
        result.leader_ = leader_;
      } else {
        result.leader_ = leaderBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.etcd.jetcd.api.ResignRequest) {
        return mergeFrom((io.etcd.jetcd.api.ResignRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.etcd.jetcd.api.ResignRequest other) {
      if (other == io.etcd.jetcd.api.ResignRequest.getDefaultInstance()) return this;
      if (other.hasLeader()) {
        mergeLeader(other.getLeader());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.etcd.jetcd.api.ResignRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.etcd.jetcd.api.ResignRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.etcd.jetcd.api.LeaderKey leader_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.etcd.jetcd.api.LeaderKey, io.etcd.jetcd.api.LeaderKey.Builder, io.etcd.jetcd.api.LeaderKeyOrBuilder> leaderBuilder_;
    /**
     * <pre>
     * leader is the leadership to relinquish by resignation.
     * </pre>
     *
     * <code>.v3electionpb.LeaderKey leader = 1;</code>
     */
    public boolean hasLeader() {
      return leaderBuilder_ != null || leader_ != null;
    }
    /**
     * <pre>
     * leader is the leadership to relinquish by resignation.
     * </pre>
     *
     * <code>.v3electionpb.LeaderKey leader = 1;</code>
     */
    public io.etcd.jetcd.api.LeaderKey getLeader() {
      if (leaderBuilder_ == null) {
        return leader_ == null ? io.etcd.jetcd.api.LeaderKey.getDefaultInstance() : leader_;
      } else {
        return leaderBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * leader is the leadership to relinquish by resignation.
     * </pre>
     *
     * <code>.v3electionpb.LeaderKey leader = 1;</code>
     */
    public Builder setLeader(io.etcd.jetcd.api.LeaderKey value) {
      if (leaderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        leader_ = value;
        onChanged();
      } else {
        leaderBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * leader is the leadership to relinquish by resignation.
     * </pre>
     *
     * <code>.v3electionpb.LeaderKey leader = 1;</code>
     */
    public Builder setLeader(
        io.etcd.jetcd.api.LeaderKey.Builder builderForValue) {
      if (leaderBuilder_ == null) {
        leader_ = builderForValue.build();
        onChanged();
      } else {
        leaderBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * leader is the leadership to relinquish by resignation.
     * </pre>
     *
     * <code>.v3electionpb.LeaderKey leader = 1;</code>
     */
    public Builder mergeLeader(io.etcd.jetcd.api.LeaderKey value) {
      if (leaderBuilder_ == null) {
        if (leader_ != null) {
          leader_ =
            io.etcd.jetcd.api.LeaderKey.newBuilder(leader_).mergeFrom(value).buildPartial();
        } else {
          leader_ = value;
        }
        onChanged();
      } else {
        leaderBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * leader is the leadership to relinquish by resignation.
     * </pre>
     *
     * <code>.v3electionpb.LeaderKey leader = 1;</code>
     */
    public Builder clearLeader() {
      if (leaderBuilder_ == null) {
        leader_ = null;
        onChanged();
      } else {
        leader_ = null;
        leaderBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * leader is the leadership to relinquish by resignation.
     * </pre>
     *
     * <code>.v3electionpb.LeaderKey leader = 1;</code>
     */
    public io.etcd.jetcd.api.LeaderKey.Builder getLeaderBuilder() {
      
      onChanged();
      return getLeaderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * leader is the leadership to relinquish by resignation.
     * </pre>
     *
     * <code>.v3electionpb.LeaderKey leader = 1;</code>
     */
    public io.etcd.jetcd.api.LeaderKeyOrBuilder getLeaderOrBuilder() {
      if (leaderBuilder_ != null) {
        return leaderBuilder_.getMessageOrBuilder();
      } else {
        return leader_ == null ?
            io.etcd.jetcd.api.LeaderKey.getDefaultInstance() : leader_;
      }
    }
    /**
     * <pre>
     * leader is the leadership to relinquish by resignation.
     * </pre>
     *
     * <code>.v3electionpb.LeaderKey leader = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.etcd.jetcd.api.LeaderKey, io.etcd.jetcd.api.LeaderKey.Builder, io.etcd.jetcd.api.LeaderKeyOrBuilder> 
        getLeaderFieldBuilder() {
      if (leaderBuilder_ == null) {
        leaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.etcd.jetcd.api.LeaderKey, io.etcd.jetcd.api.LeaderKey.Builder, io.etcd.jetcd.api.LeaderKeyOrBuilder>(
                getLeader(),
                getParentForChildren(),
                isClean());
        leader_ = null;
      }
      return leaderBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:v3electionpb.ResignRequest)
  }

  // @@protoc_insertion_point(class_scope:v3electionpb.ResignRequest)
  private static final io.etcd.jetcd.api.ResignRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.etcd.jetcd.api.ResignRequest();
  }

  public static io.etcd.jetcd.api.ResignRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResignRequest>
      PARSER = new com.google.protobuf.AbstractParser<ResignRequest>() {
    public ResignRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResignRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResignRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResignRequest> getParserForType() {
    return PARSER;
  }

  public io.etcd.jetcd.api.ResignRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

