// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.etcd.jetcd.api;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  io.etcd.jetcd.api.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  io.etcd.jetcd.api.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * version is the cluster protocol version used by the responding member.
   * </pre>
   *
   * <code>string version = 2;</code>
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * version is the cluster protocol version used by the responding member.
   * </pre>
   *
   * <code>string version = 2;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * dbSize is the size of the backend database, in bytes, of the responding member.
   * </pre>
   *
   * <code>int64 dbSize = 3;</code>
   */
  long getDbSize();

  /**
   * <pre>
   * leader is the member ID which the responding member believes is the current leader.
   * </pre>
   *
   * <code>uint64 leader = 4;</code>
   */
  long getLeader();

  /**
   * <pre>
   * raftIndex is the current raft index of the responding member.
   * </pre>
   *
   * <code>uint64 raftIndex = 5;</code>
   */
  long getRaftIndex();

  /**
   * <pre>
   * raftTerm is the current raft term of the responding member.
   * </pre>
   *
   * <code>uint64 raftTerm = 6;</code>
   */
  long getRaftTerm();
}
