// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lock.proto

package io.etcd.jetcd.api.lock;

public interface UnlockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v3lockpb.UnlockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  io.etcd.jetcd.api.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  io.etcd.jetcd.api.ResponseHeaderOrBuilder getHeaderOrBuilder();
}
